#ifndef __SAMPLES_H__
#define __SAMPLES_H__

#define SAMPLE_FLUTE 34
#define SAMPLE_TRIANGLE 39
#define SAMPLE_LOWCLARINET 40
#define SAMPLE_SELLOENSEMBLE 42
#define SAMPLE_CLEARCYMBAL 43
#define SAMPLE_CUCKOO 44
#define SAMPLE_RINGWHISTLE 48
#define SAMPLE_CREAK 50
#define SAMPLE_SPLOSH 56
#define SAMPLE_SNORTT 64

#endif
